AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket 
    
Parameters:
  bucketName:
    Description: Your environment name
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: !Ref bucketName